<?php
// Set up page title:
$this->headTitle($this->translate('Reset Password'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Reset Password') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">

    <h2><?=$this->transEsc('Reset Password') ?></h2>
    <?=$this->flashmessages() ?>

    <form id="resetpassword" class="form-reset-password" action="<?=$this->url('myresearch-reset') ?>" method="post" data-toggle="validator">
        <div class="form-group">
            <label class="control-label" for="username"><?=$this->transEsc('Username')?>:</label>
            <input type="text" name="username" id="username" class="form-control"/>
        </div>

        <?=$this->captcha()->html($this->useCaptcha) ?>
        <div class="form-group">
            <input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEscAttr('Submit')?>">
        </div>
    </form>

</div>
